qanary_component-smaph-erd/docker/Dockerfile

[ERROR] Failed to execute goal com.spotify:docker-maven-plugin:0.4.10:build (build-image) on project qa.smaph-erd: Exception caught: ADD failed: stat /var/lib/docker/tmp/docker-builder512498411/qa.smaph-erd-0.0.1.jar: no such file or directory -> [Help 1]

fix build problem

---

qanary_pipeline-template/src/main/java/eu/wdaqua/qanary/web/QanaryPipelineConfiguration.java
qanary_pipeline-template/src/main/resources/application.properties

The pipeline will not start without values for server.host or server.port in application.properties.

server host and port are required parameters

---

qanary_pipeline-template/pom.xml
qanary_pipeline-template/src/main/java/eu/wdaqua/qanary/web/QanaryQuestionAnsweringController.java
qanary_pipeline-template/src/main/resources/templates/lib/header.html
qanary_pipeline-template/src/main/resources/templates/lib/reusableforms.html
qanary_pipeline-template/src/main/resources/templates/startquestionansweringwithtextquestion.html

On `startquestionansweringwithtextquestion` for every component selected for the pipeline process the number of created Annotations is shown.
`qanary_pipeline-template` uses version 2.0.3 of qa.commons following [commit 186c06eb2906b7d8a11513a029f6192b02b20872](https://github.com/WDAqua/Qanary/commit/186c06eb2906b7d8a11513a029f6192b02b20872#diff-8dd8750b189dfef69bde0ca1c366d927).

show Annotation count

---

qanary_pipeline-template/src/main/java/eu/wdaqua/qanary/web/QanaryQuestionAnsweringController.java

The regex used in getNumberOfAnnotationsForComponent() now matches the complete component name after a leading ":" to allow for uris like "urn:qanary:component", followed by a line end.

fix(annotation count): improve regex

---

qanary_pipeline-template/src/main/resources/templates/startquestionansweringwithtextquestion.html

YASGUI no longer takes the browser focus. The focus is set to the "question" input field.

Set autofocus to question input

---

qanary_pipeline-template/src/main/java/eu/wdaqua/qanary/web/QanaryQuestionController.java

A problem was observed while running Qanary in a Docker container which many Qanary users do: While creating the resource for a new question, these URIs are pointing to the local environment within the Docker container. Therefore, the question URIs are not accessible.
Implemented solution: URIs of questions are now created with the actual host and port of the Qanary pipeline based on the external request of the user (hence, `http://localhost...` is prevented). 
Therefore, questions are now also accessible by all Qanary components even if the Qanary pipeline running inside a Docker container.

Create Question URIs with correct service host name

---

.env
qanary_pipeline-template/pom.xml

Following the recently added feature (question URIs) the `docker-compose.yml` file has to use a newer version for Qanary pipeline.
Configuration UI now uses version 0.1.0 instead of latest.

(docker): update pipeline and config-ui versions

---

.env
docker-compose.yml
qanary-configuration-frontend/.env
qanary-configuration-frontend/Dockerfile
qanary-configuration-frontend/package-lock.json
qanary-configuration-frontend/package.json
qanary-configuration-frontend/run-app.sh

When starting the Qanary configuration front end with docker the host and port of Qanary pipeline can be provided with 
`docker run -e REACT_APP_HOST=<host> -e REACT_APP_PORT=<port> qanary/qanary-configuration-frontend:1.0.0`.
or in `docker-compose.yml` as `environment:` parameter.
If no parameters are specified the UI uses the default values set in `qanary-configuration-frontend/.env`:
- REACT_APP_HOST=localhost
- REACT_APP_PORT=8080

Make configuration UI connection configurable 

---

qanary_commons/pom.xml
qanary_commons/src/main/java/eu/wdaqua/qanary/business/QanaryConfigurator.java
qanary_commons/src/main/java/eu/wdaqua/qanary/commons/QanaryQuestion.java
qanary_commons/src/test/java/qa/commons/PriorConversationTest.java
qanary_pipeline-template/pom.xml
qanary_pipeline-template/src/main/java/eu/wdaqua/qanary/QanaryPipeline.java
qanary_pipeline-template/src/main/java/eu/wdaqua/qanary/web/QanaryPipelineConfiguration.java
qanary_pipeline-template/src/main/resources/application.properties

Make the URL pointing to the OWL qa vocabulary configurable in `application.properties` or `application.local.properties`.

Configurable ontology location

---

qanary_pipeline-template/src/main/resources/application.properties

Correct the ontology location specified in `application.properties` of `qanary_pipeline-template` s.t. it can be loaded into the triplestore.

Fix Qanary Ontology Location in Properties

---

qanary_pipeline-template/src/main/java/eu/wdaqua/qanary/web/QanaryConfigurationController.java

To get information about currently available components `QanaryConfiguratoinController` offers en endpoint `/components` that returns a JSON array with names and URLs of the components.

Add controller for component list

---

qanary_commons/src/main/java/eu/wdaqua/qanary/commons/QanaryQuestion.java
qanary_pipeline-template/src/main/java/eu/wdaqua/qanary/web/QanaryGerbilController.java
qanary_pipeline-template/src/main/java/eu/wdaqua/qanary/web/QanaryQuestionAnsweringController.java
qanary_pipeline-template/src/main/java/eu/wdaqua/qanary/web/messages/RequestQuestionAnsweringProcess.java
qanary_pipeline-template/src/test/java/eu/wdaqua/qanary/QanaryQuestionAnsweringControllerTest.java

Fixed Errors in **QanaryQuestion** when:
1.  trying to retrieve a SPARQL Query, when none was in Triplestore -> **IndexOutOfBoundsException** in _getSparqlResult()_
2. trying to retrieve JSON Result ("answers" - JSONArray) when none was in Triplestore -> **NullPointerException** in _getJsonResult()_
Changed **GerbilController** to return answers as specified by dice-group (see: [dice-group/gerbil/wiki/Question-Answering](https://github.com/dice-group/gerbil/wiki/Question-Answering#web-service-interface)) 
Changed how language is handled by the GerbilController and the Pipeline to accomodate for the parameter "lang" sent by gerbil, which contains the language of the question as ISO 639-1 code (see: [dice-group/gerbil/wiki/Question-Answering](https://github.com/dice-group/gerbil/wiki/Questio …

changes for Gerbil QA

---

qanary_component-archetype/src/main/resources/archetype-resources/src/main/resources/config/application.properties
qanary_component-template/src/main/java/eu/wdaqua/qanary/component/QanaryComponentConfiguration.java
qanary_pipeline-template/src/main/java/eu/wdaqua/qanary/web/QanaryEmbeddedQaWebFrontendController.java
qanary_pipeline-template/src/main/java/eu/wdaqua/qanary/web/QanaryPipelineConfiguration.java
qanary_pipeline-template/src/main/java/eu/wdaqua/qanary/web/QanaryQuestionAnsweringController.java
qanary_pipeline-template/src/main/java/eu/wdaqua/qanary/web/StringToInsertQueryConverter.java
qanary_pipeline-template/src/main/java/eu/wdaqua/qanary/web/messages/AdditionalTriples.java
qanary_pipeline-template/src/main/resources/application.properties
qanary_pipeline-template/src/main/resources/templates/lib/reusableforms.html
qanary_pipeline-template/src/main/resources/templates/startquestionansweringwithtextquestion.html

Add the required configuration parameters to `application.properties` in Qanary component archetype.
Add getHost() method to Qanary component template to retrieve the host from the current context path instead of the hard-coded configuration in application.properties. This is required s.t. a component can register itself at the Spring Boot Admin endpoint.
Add the option to load additional triples into the triplestore before starting the question answering process.

Integrate SSL connections into Qanary component archetype and template

---

qanary_pipeline-template/src/main/java/eu/wdaqua/qanary/web/QanaryQuestionAnsweringController.java
qanary_pipeline-template/src/main/resources/templates/startquestionansweringwithtextquestion.html

Don't query the triplestore directly from the Yasgui frontend
implementation. Use the endpoint provided by the pipeline instead.
Introduce new ModelAttribute to expose the required endpoint.
Remove Authorization header fields (they are no longer needed).

use /sparql to query triplestore with yasgui

---

qanary_pipeline-template/src/main/java/eu/wdaqua/qanary/web/QanaryQuestionController.java

In the `QanaryQuestionController` questions are [written to a file using the system default character encoding](https://github.com/WDAqua/Qanary/blob/9a333985d3282d221a25aac9f9414274602621b9/qanary_pipeline-template/src/main/java/eu/wdaqua/qanary/web/QanaryQuestionController.java#L116) returned by [Charset.defaultCharset()](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/nio/charset/Charset.html#defaultCharset()). These charsets differ for each system, on Ubuntu 22.04 the default charset is `US-ASCII` while Windows 10 uses `windows-1252`:
Ubuntu 22.04:
```
jshell> import java.nio.charset.Charset;
jshell> Charset.defaultCharset();
$2 ==> US-ASCII
```
Windows 10:
```
jshell> import java.nio.charset.Charset;
jshell> Charset.defaultCharset();
$2 ==> windows-1252
```
In the …

[fix] set question file encoding to UTF-8

---

qanary_commons/src/main/java/eu/wdaqua/qanary/message/QanaryAvailableQuestions.java

When no directory for string raw question data is configured in the `application.properties` a fallback is implemented to store these files on the current execution path. Also there are no checks what files will be included.
In the default configuration the following will be returned when executing the qanary pipeline from `/opt/Qanary` and quering the `/question` api endpoint:
```sh
qanary@qanary:/opt/Qanary$ java -jar qanary_pipeline-template/target/qa.pipeline-3.1.0.jar
qanary@qanary:/opt/Qanary$ curl http://localhost:8080/question/
```
```json
{
"availableQuestions": [
"http://localhost:8080/question/pom.xml/",
"http://localhost:8080/question/README.md/",
"http://localhost:8080/question/.gitignore/",
"http://localhost:8080/question/.env/", …
```

[fix] do not return arbitrary file names in QanaryAvailableQuestions API endpoint

---

qanary_pipeline-template/pom.xml
qanary_pipeline-template/src/main/java/eu/wdaqua/qanary/web/ApplicationWebSecurityConfigurerAdapter.java
qanary_pipeline-template/src/main/java/eu/wdaqua/qanary/web/QanaryConfigurationAccessParameters.java
qanary_pipeline-template/src/main/java/eu/wdaqua/qanary/web/QanaryPipelineConfigurationController.java
qanary_pipeline-template/src/main/resources/application.properties
qanary_pipeline-template/src/main/resources/templates/hello.html
qanary_pipeline-template/src/main/resources/templates/login.html

Implement configuration access security flag for Qanary v3.
Add flag `configuration.access' to application.properties with allowed values:
* `disallow`: web access is disabled for specific pages
* `web`: web access to specific pages is enabled only with credentials 
Add corresponding credentials as `configuration.username` and `configuration.password`. Use default values if they are not set. 
---
Refactor the `/configuration` endpoint. 
* `GET`: return current configuration from environment (Json)
* `POST`: allow modification of certain parameters by passing a custom configuration (Json)
By default, access to this endpoint is restricted (see above).

Update Configuration Access

---

.gitignore
qanary_commons/pom.xml
qanary_commons/src/main/java/eu/wdaqua/qanary/business/QanaryConfigurator.java
qanary_commons/src/main/java/eu/wdaqua/qanary/message/QanaryQuestionAnsweringFinished.java
qanary_commons/src/main/resources/queries/select_base_triples_of_component_annotations_in_a_graph.rq
qanary_commons/src/test/java/qa/commons/RuntimeDependenciesTest.java
qanary_component-template/pom.xml
qanary_pipeline-template/pom.xml
qanary_pipeline-template/src/main/java/eu/wdaqua/qanary/exceptions/AdditionalTriplesCouldNotBeAdded.java
qanary_pipeline-template/src/main/java/eu/wdaqua/qanary/web/QanaryComponentsManagementController.java
qanary_pipeline-template/src/main/java/eu/wdaqua/qanary/web/QanaryPipelineConfiguration.java
qanary_pipeline-template/src/main/java/eu/wdaqua/qanary/web/QanaryQuestionAnsweringController.java
qanary_pipeline-template/src/main/java/eu/wdaqua/qanary/web/QanarySparqlProtocolController.java
qanary_pipeline-template/src/main/java/eu/wdaqua/qanary/web/messages/AdditionalTriples.java
qanary_pipeline-template/src/main/java/eu/wdaqua/qanary/web/messages/RequestQuestionAnsweringProcess.java
qanary_pipeline-template/src/main/resources/application.properties
qanary_pipeline-template/src/main/resources/templates/lib/header.html
qanary_pipeline-template/src/main/resources/templates/startquestionansweringwithtextquestion.html
qanary_pipeline-template/src/test/java/eu/wdaqua/qanary/QanaryQuestionAnsweringControllerTest.java
qanary_pipeline-template/src/test/java/eu/wdaqua/qanary/RuntimeDependenciesTest.java

also new versions: `qanary.commons` v3.7.0, `qanary.component` v3.7.0

Qanary pipeline v3.6.0 with additional helpers

---

qanary_commons/src/main/java/eu/wdaqua/qanary/commons/triplestoreconnectors/QanaryTripleStoreConnector.java
qanary_commons/src/main/resources/queries/insert_one_AnnotationOfTypedLiteral.rq

Required change to QanaryTriplestoreConnector.java to extend the Qanary Platypus Wrapper QB component

add support for AnnotationOfTypedLiteral

---

qanary_commons/pom.xml
qanary_commons/src/main/java/eu/wdaqua/qanary/commons/triplestoreconnectors/QanaryTripleStoreConnector.java

The latest merge of the https://github.com/WDAqua/Qanary/pull/265 PR lead to some Javadoc issues.
They should now be resolved.
Built the project and all artifacts successfully with `mvn clean install -Dgpg.skip`

Resolved Javadoc errors

---

qanary_pipeline-template/pom.xml
qanary_pipeline-template/src/main/java/eu/wdaqua/qanary/QanaryComponentRegistrationChangeNotifier.java
qanary_pipeline-template/src/main/java/eu/wdaqua/qanary/web/QanaryQuestionAnsweringController.java
qanary_pipeline-template/src/main/resources/templates/lib/reusableforms.html

> Implement a method to indicate whether a component is accessible or not
Fixed by:
- Passing the Map<Component name, status> to the Thymeleaf template instead of List
- Each request to /startquestionansweringwithtextquestion calls the cached method that returns that map
- Offline components can't be selected and appear in a darker gre

Fix registration for questionanswering frontend
