WDAqua/Qanary

qanary_pipeline-template/.gitignore
qanary_pipeline-template/pom.xml
qanary_pipeline-template/src/main/java/eu/wdaqua/qanary/QanaryPipeline.java
qanary_pipeline-template/src/main/java/eu/wdaqua/qanary/web/QanaryGerbilController.java
qanary_pipeline-template/src/main/java/eu/wdaqua/qanary/web/QanaryPipelineConfiguration.java
qanary_pipeline-template/src/main/java/eu/wdaqua/qanary/web/QanaryQuestionAnsweringController.java
qanary_pipeline-template/src/main/java/eu/wdaqua/qanary/web/QanaryQuestionController.java
qanary_pipeline-template/src/main/resources/application.properties
qanary_pipeline-template/src/main/resources/templates/lib/header.html
qanary_pipeline-template/src/main/resources/templates/startquestionansweringwithtextquestion.html
qanary_pipeline-template/src/test/java/qa/pipeline/QanaryQuestionControllerTest.java

Beta version of an integrated SPARQL query interface

Frontend yasgui beta

---

pom.xml
qanary_component-archetype/pom.xml
qanary_component-archetype/src/main/resources/archetype-resources/src/main/java/Application.java
qanary_component-archetype/src/main/resources/archetype-resources/src/main/resources/config/application.properties
qanary_component-template/src/main/java/eu/wdaqua/qanary/component/QanaryComponentConfiguration.java
qanary_component-template/src/main/java/eu/wdaqua/qanary/component/QanaryService.java

qanary_component-archetype version 1.1.0:
Components built using qanary_component-template list their current configuration parameters when started.

Archetype component configuration

---

qanary_component-archetype/src/main/resources/archetype-resources/pom.xml
qanary_component-archetype/src/main/resources/archetype-resources/src/main/resources/config/application.properties
qanary_component-archetype/src/main/resources/archetype-resources/src/test/java/TestQanaryServiceController.java

the component archetype was changed according to recent updates to Qanary question answering components
Java version 11
modified controller tests
config file includes client.instance.service-base-url

Update component archetype

---

qanary_commons/src/main/java/eu/wdaqua/qanary/commons/QanaryQuestion.java
qanary_commons/src/main/java/eu/wdaqua/qanary/commons/QanaryQuestionTextual.java
qanary_pipeline-template/src/main/java/eu/wdaqua/qanary/web/QanaryQuestionAnsweringController.java
qanary_pipeline-template/src/main/java/eu/wdaqua/qanary/web/QanaryStandardWebParameters.java
qanary_pipeline-template/src/main/java/eu/wdaqua/qanary/web/messages/RequestQuestionAnsweringProcess.java

Variations of previousProcessGraph are renamed to priorConversation.

refactor: make parameter naming consistent

---

qanary_commons/src/main/java/eu/wdaqua/qanary/commons/QanaryQuestion.java

Update how the Json Answer for a question answering process is retrieved.

Update Retrieval of Answer Json 

---

qanary_commons/pom.xml
qanary_commons/src/main/java/eu/wdaqua/qanary/commons/triplestoreconnectors/QanaryTripleStoreConnectorVirtuoso.java
qanary_commons/src/main/java/eu/wdaqua/qanary/commons/triplestoreconnectors/README.adoc
qanary_pipeline-template/pom.xml
qanary_pipeline-template/src/main/resources/application.properties

see the documentation in the folder qanary_commons/triplestoreconnectors

add support for the Openlink Virtuoso triplestore

---

qanary_commons/pom.xml
qanary_commons/src/main/java/eu/wdaqua/qanary/commons/QanaryUtils.java
qanary_commons/src/main/java/eu/wdaqua/qanary/commons/triplestoreconnectors/QanaryTripleStoreConnector.java
qanary_commons/src/main/java/eu/wdaqua/qanary/commons/triplestoreconnectors/README.adoc
qanary_commons/src/main/resources/queries/insert_one_AnnotationOfAnswerJson.rq
qanary_commons/src/main/resources/queries/select_highestScore_AnnotationOfAnswerSPARQL.rq

Changes for the new SPARQL Executer and add some warning for the deprecated methods

142 sparql executer update

---

qanary_commons/pom.xml
qanary_commons/src/main/resources/queries/insert_one_AnnotationOfAnswerJson.rq

* add missing PREFIX for the SPARQLExecuter

qa.commons 3.5.3

---

qanary_pipeline-template/src/main/resources/application.properties

tiny update for fix-gerbil-not-accessible

add logging output for rejected request

---

.github/workflows/docker-deployment.yml

The autodeployment has been updated to exit with an error, if the pipeline can't be deployed.

Updated docker-service-updater action to v0.1.5

---

qanary_pipeline-template/pom.xml
qanary_pipeline-template/src/main/java/eu/wdaqua/qanary/web/ApplicationWebSecurityConfigurerAdapter.java
qanary_pipeline-template/src/main/java/eu/wdaqua/qanary/web/CorsConfigurationOnCondition.java
qanary_pipeline-template/src/main/java/eu/wdaqua/qanary/web/QanaryPipelineConfiguration.java
qanary_pipeline-template/src/main/resources/application.properties
qanary_pipeline-template/src/test/java/eu/wdaqua/qanary/web/CorsConfigurationOnConditionTest.java

developers are enabled now to influence the CORS rules for all endpoints at once
see https://github.com/WDAqua/Qanary/wiki/How-do-I-handle-CORS-regulations%3F for further details

Qanary pipeline v3.7.0: custom CORS defintions

---

qanary_component-template/pom.xml
qanary_component-template/src/main/java/eu/wdaqua/qanary/component/QanaryComponentDescriptionController.java

* warning message improved
* typo of method name fixed

Qanary.component v3.7.1: tiny improvement

---

qanary_pipeline-template/pom.xml

Fix issue #154   by update dependency org.yaml:snakeyaml:1.33 @anbo-de

Fix CVE dependency issue

---

.github/dependabot.yml
.github/workflows/docker-deployment.yml

The GitHub Action used to deploy a Qanary Pipeline instance has been updated. Additionally, Dependabot has been
integrated to check for updates on the used GitHub Actions.

Updated deployment action + Dependabot integration for updates

---

qanary_commons/src/main/resources/queries/select_all_AnnotationOfSpotInstance.rq

There was a small syntax error.

Fixed syntax error

---

qanary_commons/src/main/resources/queries/insert_one_AnnotationOfQuestionLanguage.rq
qanary_commons/src/main/resources/queries/insert_one_AnnotationOfQuestionTranslation.rq

- created INSERT-Queries for types `AnnotationOfQuestionTranslation` and `AnnotationOfQuestionLanguage`

Created INSERT-Queries for types `AnnotationOfQuestionTranslation` and `AnnotationOfQuestionLanguage`

---

qanary_component-template/pom.xml

add missing dependencies for the QanaryComponentDescriptionController

qa.component 3.7.3

---

qanary_commons/pom.xml
qanary_commons/src/main/resources/queries/select_all_AnnotationOfAnswerJson.rq

Due to the [issue](https://github.com/WSE-research/team-tasks/issues/387) the SELECT-Query is updated and the version is incremented: 3.9.0 -> 3.9.1

Bugfix: SELECT-Query for type `AnnotationOfAnswerJSON`

---

qanary_pipeline-template/src/main/java/eu/wdaqua/qanary/web/ApplicationWebSecurityConfigurerAdapter.java

Allow access to the relevant path.

Allow removing of components in Admin Dashboard 

---

.github/workflows/maven.yml
qanary_commons/pom.xml
qanary_commons/src/main/java/eu/wdaqua/qanary/business/TriplestoreEndpointIdentifier.java
qanary_commons/src/main/java/eu/wdaqua/qanary/commons/QanaryQuestion.java
qanary_commons/src/main/java/eu/wdaqua/qanary/commons/ontology/TextPositionSelector.java
qanary_commons/src/main/java/eu/wdaqua/qanary/message/QanaryQuestionCreated.java

Adjusted maven.yml as well as the Qanary commons pom + classes for deployment to the maven central repository.

Maven central deployment

---

qanary_commons/pom.xml
qanary_commons/src/main/java/eu/wdaqua/qanary/commons/QanaryUtils.java
service_config/build_images.sh

- fixed Javadoc
- increment version to 3.11.5
- adjusted image building to skip gpg signing

Fixed Javadoc, increment version, adjusted image building

---

qanary_pipeline-template/Dockerfile
qanary_pipeline-template/pom.xml
service_config/build_images.sh

qa.pipeline 3.8.4:
add ARM support to pipeline

ARM support

---

service_config/build_images.sh

BUGFIX
ARM support to pipeline

qa.pipeline 3.8.4

---

qanary_commons/pom.xml
qanary_commons/src/main/java/eu/wdaqua/qanary/commons/QanaryQuestion.java
qanary_commons/src/main/resources/queries/insert_required_triples.rq

v3.14.0
- added an INSERT SPARQL query which contains required triples

Added query to insert required triples on graph init.

---

.github/workflows/maven.yml
qanary_commons/pom.xml
qanary_component-parent/pom.xml
qanary_component-template/pom.xml
qanary_pipeline-template/pom.xml

As the old approach is deprecated, we establish the new one.

Renew release process
